# Generated by Django 5.2.8 on 2025-12-17 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Workout', 'Workout'), ('Seminar', 'Seminar'), ('Competition', 'Competition'), ('Offer', 'Offer')], default='Workout', max_length=20)),
                ('event_category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('trainer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(choices=[('Gym', 'Gym'), ('Online', 'Online')], default='Gym', max_length=10)),
                ('max_participants', models.PositiveIntegerField()),
                ('registration_deadline', models.DateTimeField()),
                ('fee', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Draft', 'Draft'), ('Published', 'Published')], default='Upcoming', max_length=20)),
                ('registered_members', models.ManyToManyField(blank=True, related_name='registered_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
