# Generated by Django 5.2.8 on 2025-12-18 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('superadmin', '0008_remove_gym_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
    ]
