# Generated by Django 5.2.8 on 2025-12-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveBigIntegerField(),
        ),
    ]
