# Generated by Django 5.2.8 on 2025-12-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_max_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_gym_member', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('current_gym_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fitness_level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Athlete', 'Athlete')], max_length=20, null=True)),
                ('years_of_training', models.PositiveIntegerField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('terms', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Card', 'Card'), ('Online Gateway', 'Online Gateway')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('registration_source', models.CharField(default='Public', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(default='Registered', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
        ),
    ]
