# Generated by Django 5.2.8 on 2025-12-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_location_event_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fee',
        ),
        migrations.AddField(
            model_name='event',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Card', 'Card'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
