# Generated by Django 5.2.8 on 2025-12-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_fee_event_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qr_codes/'),
        ),
        migrations.AddField(
            model_name='event',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]