# Generated by Django 5.2.8 on 2025-11-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_packageplan_membershipplan'),
        ('members', '0002_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joining_date', models.DateField()),
                ('membership_start_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='members.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.membershipplan')),
            ],
        ),
    ]