# Generated by Django 5.2.8 on 2025-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_email_alter_member_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
