# Generated by Django 5.2.8 on 2025-11-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], max_length=50),
        ),
    ]
