# Generated by Django 5.2.8 on 2025-11-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_membershiphistory_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='membership_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
