# Generated by Django 5.2.8 on 2025-11-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_membershiphistory_membership_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiphistory',
            name='membership_end_date',
        ),
    ]
