# Generated by Django 5.2.8 on 2025-11-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_membershiphistory_membership_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiphistory',
            name='joining_date',
        ),
    ]
