# Generated by Django 5.2.8 on 2025-11-21 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_membershiphistory_joining_date'),
        ('trainers', '0005_alter_trainer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField()),
                ('trainer_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gym_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pt_start_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_trainer', to='members.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer')),
            ],
        ),
    ]
