# Generated by Django 5.2.8 on 2025-12-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
