# Generated by Django 5.2.8 on 2025-12-03 05:10

from django.db import migrations, models
from django.utils import timezone


def generate_member_ids(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    year = timezone.now().strftime("%y")
    
    existing_ids = Member.objects.filter(member_id__startswith=f"MEM-{year}-").values_list('member_id', flat=True)
    max_count = 0
    for mid in existing_ids:
        try:
            count = int(mid.split('-')[-1])
            if count > max_count:
                max_count = count
        except (ValueError, IndexError):
            continue

    for member in Member.objects.filter(models.Q(member_id__isnull=True) | models.Q(member_id="")):
        max_count += 1
        counter = str(max_count).zfill(6)
        member.member_id = f"MEM-{year}-{counter}"
        member.save(update_fields=['member_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(generate_member_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]