# Generated by Django 5.2.8 on 2025-12-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_member_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaltrainer',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('other', 'Other')], max_length=50),
        ),
    ]
