# Generated by Django 5.2.8 on 2025-12-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_remove_member_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('other', 'Other')], max_length=50),
        ),
    ]
