# Generated by Django 5.2.8 on 2025-12-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_membershiphistory_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
