# Generated by Django 5.2.8 on 2025-12-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_remove_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='add_on_days',
            field=models.IntegerField(default=0),
        ),
    ]
