# Generated by Django 5.2.8 on 2025-12-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_membershiphistory_add_on_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
