# Generated by Django 5.2.8 on 2025-12-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_membershiphistory_status_personaltrainer_status'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
        migrations.AddField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
    ]