# Generated by Django 5.2.8 on 2025-12-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_emergencycontact_gym_medicalhistory_gym_member_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
