# Generated by Django 5.2.8 on 2025-12-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_gympayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymPayment',
        ),
    ]
