# Generated by Django 5.2.8 on 2025-11-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='membership_history',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
