# Generated by Django 5.2.8 on 2025-12-15 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_delete_gympayment'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member'),
        ),
    ]
