# Generated by Django 5.2.8 on 2025-12-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_payment_member'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.membershiphistory'),
        ),
    ]
