# Generated by Django 5.2.8 on 2025-12-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_payment_membership_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='membership_history',
        ),
    ]
