# Generated by Django 5.2.8 on 2025-12-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_payment_comment_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
