# Generated by Django 5.2.8 on 2025-12-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_payment_membership_history'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='personal_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.personaltrainer'),
        ),
    ]