# Generated by Django 5.2.8 on 2025-12-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_payment_follow_up_date'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
    ]
