# Generated by Django 5.2.8 on 2025-12-08 10:02

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='user',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]