# Generated by Django 5.2.8 on 2025-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20251208_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gym_logos/'),
        ),
        migrations.AddField(
            model_name='gym',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
