# Generated by Django 5.2.8 on 2025-12-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_gym_gym_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
