# Generated by Django 5.2.8 on 2025-12-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_gym_gym_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='gym_id_prefix',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
