# Generated by Django 5.2.8 on 2025-12-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_gym_contact_person_gym_gstin_gym_logo_gym_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='domain_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='gym',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.subscriptionplan'),
        ),
    ]
