# Generated by Django 5.2.8 on 2025-12-08 10:17

from django.db import migrations

def create_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('superadmin', 'SubscriptionPlan')
    SubscriptionPlan.objects.create(name='Basic', price=1000, duration_months=1)
    SubscriptionPlan.objects.create(name='Standard', price=2500, duration_months=3)
    SubscriptionPlan.objects.create(name='Premium', price=5000, duration_months=6)

class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_subscriptionplan_gym_domain_url_gym_status_and_more'),
    ]

    operations = [
        migrations.RunPython(create_subscription_plans),
    ]