# Generated by Django 5.2.8 on 2025-12-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration',
        ),
        migrations.AddField(
            model_name='gym',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='pincode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.IntegerField(default=1, help_text='Duration in months'),
        ),
    ]
