# Generated by Django 5.2.8 on 2025-12-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_remove_subscriptionplan_duration_gym_area_gym_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymadmin',
            name='Department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gymadmin',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gymadmin',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gymadmin',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymadmin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gym_admin_photos/'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
