# Generated by Django 5.2.8 on 2025-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_gymadmin_department_gymadmin_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
