# Generated by Django 5.2.8 on 2025-12-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_gym_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('frozen', 'Frozen')], default='expired', max_length=10),
        ),
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='superadmin.gym')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.subscriptionplan')),
            ],
        ),
    ]
