# Generated by Django 5.2.8 on 2025-12-13 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_alter_gym_status_gymsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='status',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='superadmin.gym'),
        ),
        migrations.DeleteModel(
            name='GymSubscription',
        ),
    ]
