# Generated by Django 5.2.8 on 2025-12-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_remove_gym_status_subscriptionplan_gym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField(default=1, help_text='Duration in months')),
                ('features', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GymSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='superadmin.gym')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.subscription')),
            ],
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
