# Generated by Django 5.2.8 on 2025-11-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_dietplan_workoutplan_rename_name_packageplan_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='daily_calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='target',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('fat_loss', 'Fat Loss')], default='weight_loss', max_length=20),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
