# Generated by Django 5.2.8 on 2025-11-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='duration_in_days',
            field=models.IntegerField(default=0),
        ),
    ]
