# Generated by Django 5.2.8 on 2025-11-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_packageplan_duration_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageplan',
            name='duration_in_days',
            field=models.FloatField(default=0),
        ),
    ]
