# Generated by Django 5.2.8 on 2025-11-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_packageplan_duration_in_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageplan',
            name='duration_in_days',
        ),
        migrations.RemoveField(
            model_name='packageplan',
            name='duration_in_months',
        ),
        migrations.AddField(
            model_name='packageplan',
            name='duration',
            field=models.CharField(choices=[('1_day', '1 Day'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], default='1_month', max_length=20),
        ),
    ]
