# Generated by Django 5.2.8 on 2025-11-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_packageplan_duration_in_days_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackagePlan',
            new_name='MembershipPlan',
        ),
    ]
