# Generated by Django 5.2.8 on 2025-11-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_packageplan_membershipplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
