# Generated by Django 5.2.8 on 2025-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_membershipplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='add_on_days',
            field=models.IntegerField(default=0),
        ),
    ]
