# Generated by Django 5.2.8 on 2025-12-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_membershipplan_add_on_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipplan',
            old_name='price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
