# Generated by Django 5.2.8 on 2025-11-18 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_address_trainer_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
