# Generated by Django 5.2.8 on 2025-11-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_trainer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
