# Generated by Django 5.2.8 on 2025-12-03 05:25

from django.db import migrations, models
from django.utils import timezone

def generate_trainer_ids(apps, schema_editor):
    Trainer = apps.get_model('trainers', 'Trainer')
    for trainer in Trainer.objects.all():
        current_year = timezone.now().strftime('%y')
        last_trainer = Trainer.objects.filter(trainer_id__startswith=f'TRN-{current_year}').order_by('-trainer_id').first()
        if last_trainer and last_trainer.trainer_id:
            last_id_int = int(last_trainer.trainer_id.split('-')[-1])
            new_id_int = last_id_int + 1
        else:
            new_id_int = 1
        trainer.trainer_id = f'TRN-{current_year}-{new_id_int:06d}'
        trainer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_trainer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RunPython(generate_trainer_ids),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]