# Generated by Django 5.2.8 on 2025-12-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_trainer_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
