# Generated by Django 5.2.8 on 2025-12-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('trainers', '0007_alter_trainer_trainer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.gym'),
        ),
    ]