# Generated by Django 5.2.8 on 2025-12-02 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0012_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberattendance',
            name='date',
        ),
        migrations.AddField(
            model_name='memberattendance',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='memberattendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member'),
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='status',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=10),
        ),
    ]
