# Generated by Django 5.2.8 on 2025-12-02 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_memberattendance_date_and_more'),
        ('trainers', '0005_alter_trainer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerattendance',
            name='date',
        ),
        migrations.AddField(
            model_name='trainerattendance',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainerattendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='status',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='trainers.trainer'),
        ),
    ]
