# Generated by Django 5.2.8 on 2025-11-13 11:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='interested_in',
            field=models.CharField(choices=[('gym', 'Gym'), ('zumba', 'Zumba'), ('personal_training', 'Personal Training'), ('yoga', 'Yoga'), ('crossfit', 'CrossFit')], default='gym', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('other', 'Other')], default='walk_in', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], default='pending', max_length=20),
        ),
    ]
