# Generated by Django 5.2.8 on 2025-12-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_enquiry_gym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='assigned_to',
        ),
    ]
