# Generated by Django 5.2.8 on 2025-12-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_added_by_expense_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurring_cycle',
        ),
    ]
